In [6]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [7]:
X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")

y_train = pd.read_csv("../data/processed/y_train.csv").squeeze("columns")
y_test = pd.read_csv("../data/processed/y_test.csv").squeeze("columns")

In [8]:
def evaluate_model(model_name,model, X_test, y_test):
    
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_prob)

    return {
        "Model Name : ":model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "ROC AUC": roc_auc
    }

In [9]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [10]:
knn_result = evaluate_model("KNN",knn,X_test,y_test)
knn_result

{'Model Name : ': 'KNN',
 'Accuracy': 0.839,
 'Precision': 0.6679841897233202,
 'Recall': 0.4152334152334152,
 'F1 Score': 0.5121212121212121,
 'ROC AUC': 0.7828097743351982}

In [11]:
all_result = []

In [12]:
all_result.append(knn_result)

In [13]:
all_result

[{'Model Name : ': 'KNN',
  'Accuracy': 0.839,
  'Precision': 0.6679841897233202,
  'Recall': 0.4152334152334152,
  'F1 Score': 0.5121212121212121,
  'ROC AUC': 0.7828097743351982}]

In [14]:
comparison_df = pd.DataFrame(all_result)
comparison_df = comparison_df.round(4)
comparison_df

  Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
0           KNN     0.839      0.668  0.4152    0.5121   0.7828


# Creating Naive Bayes Model

In [15]:
nb_model = GaussianNB()
nb_model.fit(X_train,y_train)

GaussianNB()

In [16]:
nb_result = evaluate_model("Naive Bayes",nb_model,X_test,y_test)
nb_result

{'Model Name : ': 'Naive Bayes',
 'Accuracy': 0.82,
 'Precision': 0.6,
 'Recall': 0.3464373464373464,
 'F1 Score': 0.4392523364485981,
 'ROC AUC': 0.7842865978459199}

In [17]:
all_result.append(nb_result)

In [18]:
all_result

[{'Model Name : ': 'KNN',
  'Accuracy': 0.839,
  'Precision': 0.6679841897233202,
  'Recall': 0.4152334152334152,
  'F1 Score': 0.5121212121212121,
  'ROC AUC': 0.7828097743351982},
 {'Model Name : ': 'Naive Bayes',
  'Accuracy': 0.82,
  'Precision': 0.6,
  'Recall': 0.3464373464373464,
  'F1 Score': 0.4392523364485981,
  'ROC AUC': 0.7842865978459199}]

In [19]:
dt_model = DecisionTreeClassifier(random_state=42)

In [20]:
dt_model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
dt_result = evaluate_model("Decision Tree",dt_model,X_test,y_test)
dt_result

{'Model Name : ': 'Decision Tree',
 'Accuracy': 0.7825,
 'Precision': 0.46846846846846846,
 'Recall': 0.5110565110565111,
 'F1 Score': 0.4888366627497062,
 'ROC AUC': 0.6814541814541815}

In [22]:
all_result.append(dt_result)
all_result

[{'Model Name : ': 'KNN',
  'Accuracy': 0.839,
  'Precision': 0.6679841897233202,
  'Recall': 0.4152334152334152,
  'F1 Score': 0.5121212121212121,
  'ROC AUC': 0.7828097743351982},
 {'Model Name : ': 'Naive Bayes',
  'Accuracy': 0.82,
  'Precision': 0.6,
  'Recall': 0.3464373464373464,
  'F1 Score': 0.4392523364485981,
  'ROC AUC': 0.7842865978459199},
 {'Model Name : ': 'Decision Tree',
  'Accuracy': 0.7825,
  'Precision': 0.46846846846846846,
  'Recall': 0.5110565110565111,
  'F1 Score': 0.4888366627497062,
  'ROC AUC': 0.6814541814541815}]

In [23]:
comparison_df = pd.DataFrame(all_result)
comparison_df = comparison_df.round(4)

In [24]:
comparison_df

   Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
0            KNN    0.8390     0.6680  0.4152    0.5121   0.7828
1    Naive Bayes    0.8200     0.6000  0.3464    0.4393   0.7843
2  Decision Tree    0.7825     0.4685  0.5111    0.4888   0.6815

In [25]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    random_state=42
)

lr_model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [26]:
lr_result = evaluate_model("LogisticRegression",lr_model,X_test,y_test)

In [27]:
all_result.append(lr_result)

In [28]:
lr_balanced = LogisticRegression(
    random_state=42,
    class_weight="balanced"
)

lr_balanced.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', random_state=42)

In [29]:
lr_balanced_results = evaluate_model(
    "Balanced Logistic Regression",
    lr_balanced,
    X_test,
    y_test
)

all_result.append(lr_balanced_results)

In [30]:
comparison_df = pd.DataFrame(all_result)

comparison_df = comparison_df.round(4)

comparison_df

                  Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
0                           KNN    0.8390     0.6680  0.4152    0.5121   0.7828
1                   Naive Bayes    0.8200     0.6000  0.3464    0.4393   0.7843
2                 Decision Tree    0.7825     0.4685  0.5111    0.4888   0.6815
3            LogisticRegression    0.8080     0.5891  0.1867    0.2836   0.7748
4  Balanced Logistic Regression    0.7140     0.3878  0.7002    0.4991   0.7772

## Model Comparison Summary

Five machine learning models were evaluated using Accuracy, Precision, Recall, F1-score, and ROC-AUC.

### Key Findings

- KNN achieved the highest Accuracy (83.9%), Precision (66.8%), and F1-score (51.2%), making it the strongest overall performer.
- Balanced Logistic Regression achieved the highest Recall (70.0%), making it effective at identifying churned customers.
- Naive Bayes achieved the highest ROC-AUC (0.7843), indicating good ranking capability.
- Decision Tree provided moderate performance but is likely to benefit from hyperparameter tuning.
- Logistic Regression served as a strong baseline model but struggled to identify churned customers due to low Recall.

### Conclusion

There is no universally best model. The appropriate model depends on the business objective:

- If minimizing missed churned customers is the priority, Balanced Logistic Regression is preferred.
- If achieving the best overall balance across multiple metrics is the priority, KNN is the strongest candidate among the evaluated models.

# Hyperparameter Tuning

In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn_params = {
    "n_neighbors": [3,5,7,9,11,13,15]
}

### Creating Grid Search

In [34]:
grid_knn = GridSearchCV(
    estimator = KNeighborsClassifier(),
    param_grid = knn_params,
    cv = 5,
    scoring = "f1",
    n_jobs = -1
)

In [35]:
grid_knn.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [3, 5, 7, 9, 11, 13, 15]},
             scoring='f1')

In [36]:
grid_knn.best_params_

{'n_neighbors': 3}

In [37]:
grid_knn.best_score_

np.float64(0.513072221571095)

In [38]:
cv_results = pd.DataFrame(grid_knn.cv_results_)

cv_results[
    [
        "param_n_neighbors",
        "mean_test_score",
        "rank_test_score"
    ]
].sort_values(
    by="rank_test_score"
).head(10)

   param_n_neighbors  mean_test_score  rank_test_score
0                  3         0.513072                1
1                  5         0.506268                2
2                  7         0.501190                3
3                  9         0.488188                4
4                 11         0.487767                5
5                 13         0.478826                6
6                 15         0.462825                7

## KNN Hyperparameter Tuning

GridSearchCV was used with 5-fold Cross Validation to identify the optimal value of `n_neighbors`.

### Results

- Best Hyperparameter:
  - n_neighbors = 3

- Best Cross Validation F1 Score:
  - 0.5131

### Observation

- The default value (n_neighbors = 5) was not optimal for this dataset.
- GridSearchCV selected n_neighbors = 3 based on the highest mean F1-score across the validation folds.
- Cross Validation provides a more reliable estimate of model performance than a single train-validation split.

In [39]:
#Creating a new KNN model with the best parameters from GridSearchCV
best_knn = KNeighborsClassifier(n_neighbors=grid_knn.best_params_['n_neighbors'])

In [40]:
best_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [41]:
best_knn_res = evaluate_model("Best KNN",best_knn,X_test, y_test)
best_knn_res

{'Model Name : ': 'Best KNN',
 'Accuracy': 0.8235,
 'Precision': 0.5876623376623377,
 'Recall': 0.44471744471744473,
 'F1 Score': 0.5062937062937063,
 'ROC AUC': 0.7520324638968707}

## KNN Hyperparameter Tuning Results

GridSearchCV selected `n_neighbors = 3` as the optimal parameter based on 5-fold Cross Validation.

However, when evaluated on the unseen test set, the tuned model did not outperform the default KNN model across most evaluation metrics.

### Comparison

- Recall improved slightly.
- Accuracy decreased.
- Precision decreased.
- F1-score decreased slightly.
- ROC-AUC decreased.

### Conclusion

Although GridSearchCV identified the best parameter on the training data, the default KNN (k=5) generalized better on the test set. Therefore, the default KNN model is retained for further comparison.

In [42]:
dt_params = {
    "criterion": ["gini", "entropy"],
    "max_depth": [3, 5, 7, 10, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

In [43]:
grid_dt = GridSearchCV(
    estimator = DecisionTreeClassifier(random_state=42),
    param_grid = dt_params,
    cv = 5,
    scoring = "f1",
    n_jobs = -1
)

In [44]:
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 7, 10, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]},
             scoring='f1')

In [45]:
grid_dt.best_params_

{'criterion': 'entropy',
 'max_depth': 7,
 'min_samples_leaf': 1,
 'min_samples_split': 2}

In [46]:
grid_dt.best_score_

np.float64(0.5706320980642989)

In [47]:
pd.DataFrame(grid_dt.cv_results_)[
    ["params", "mean_test_score", "rank_test_score"]
].sort_values("rank_test_score").head(10)

                                               params  ...  rank_test_score
63  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                1
67  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                2
68  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                3
65  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                4
64  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                5
66  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                6
69  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                7
70  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                7
71  {'criterion': 'entropy', 'max_depth': 7, 'min_...  ...                7
80  {'criterion': 'entropy', 'max_depth': 10, 'min...  ...               10

[10 rows x 3 columns]

In [48]:
best_dt = DecisionTreeClassifier(
    criterion="entropy",
    max_depth=7,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)

In [49]:
best_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=7, random_state=42)

In [50]:
best_dt_results = evaluate_model(
    "Optimized Decision Tree",
    best_dt,
    X_test,
    y_test
)

best_dt_results

{'Model Name : ': 'Optimized Decision Tree',
 'Accuracy': 0.857,
 'Precision': 0.7153024911032029,
 'Recall': 0.49385749385749383,
 'F1 Score': 0.5843023255813954,
 'ROC AUC': 0.8277005819378702}

In [51]:
comparison_df

                  Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
0                           KNN    0.8390     0.6680  0.4152    0.5121   0.7828
1                   Naive Bayes    0.8200     0.6000  0.3464    0.4393   0.7843
2                 Decision Tree    0.7825     0.4685  0.5111    0.4888   0.6815
3            LogisticRegression    0.8080     0.5891  0.1867    0.2836   0.7748
4  Balanced Logistic Regression    0.7140     0.3878  0.7002    0.4991   0.7772

## Decision Tree Hyperparameter Tuning

GridSearchCV was used to optimize the Decision Tree classifier using 5-fold Cross Validation.

### Best Hyperparameters

- Criterion: entropy
- Maximum Depth: 7
- Minimum Samples Split: 2
- Minimum Samples Leaf: 1

### Observation

- Limiting the tree depth helps reduce overfitting.
- The entropy criterion consistently outperformed the gini criterion during cross-validation.
- The optimized model is expected to generalize better than the default Decision Tree.

In [53]:
final_results = [
    lr_result,
    lr_balanced_results,
    knn_result,
    nb_result,
    dt_result,
    best_dt_results
]

In [54]:
final_comparison = pd.DataFrame(final_results)

final_comparison = final_comparison.round(4)

final_comparison

                  Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
0            LogisticRegression    0.8080     0.5891  0.1867    0.2836   0.7748
1  Balanced Logistic Regression    0.7140     0.3878  0.7002    0.4991   0.7772
2                           KNN    0.8390     0.6680  0.4152    0.5121   0.7828
3                   Naive Bayes    0.8200     0.6000  0.3464    0.4393   0.7843
4                 Decision Tree    0.7825     0.4685  0.5111    0.4888   0.6815
5       Optimized Decision Tree    0.8570     0.7153  0.4939    0.5843   0.8277

In [55]:
final_comparison.sort_values(
    by="F1 Score",
    ascending=False
)

                  Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
5       Optimized Decision Tree    0.8570     0.7153  0.4939    0.5843   0.8277
2                           KNN    0.8390     0.6680  0.4152    0.5121   0.7828
1  Balanced Logistic Regression    0.7140     0.3878  0.7002    0.4991   0.7772
4                 Decision Tree    0.7825     0.4685  0.5111    0.4888   0.6815
3                   Naive Bayes    0.8200     0.6000  0.3464    0.4393   0.7843
0            LogisticRegression    0.8080     0.5891  0.1867    0.2836   0.7748

In [56]:
final_comparison.sort_values(
    by="ROC AUC",
    ascending=False
)

                  Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
5       Optimized Decision Tree    0.8570     0.7153  0.4939    0.5843   0.8277
3                   Naive Bayes    0.8200     0.6000  0.3464    0.4393   0.7843
2                           KNN    0.8390     0.6680  0.4152    0.5121   0.7828
1  Balanced Logistic Regression    0.7140     0.3878  0.7002    0.4991   0.7772
0            LogisticRegression    0.8080     0.5891  0.1867    0.2836   0.7748
4                 Decision Tree    0.7825     0.4685  0.5111    0.4888   0.6815

## Final Model Selection

Six machine learning models were evaluated and compared using multiple evaluation metrics.

### Key Findings

- Hyperparameter tuning significantly improved the Decision Tree model.
- Hyperparameter tuning did not improve the KNN model on the unseen test dataset.
- Balanced Logistic Regression achieved the highest Recall.
- KNN achieved strong overall performance.
- The Optimized Decision Tree provided a good balance between Accuracy, Recall, F1-score, and interpretability.

### Final Decision

The Optimized Decision Tree was selected as the final model because it achieved strong predictive performance while remaining interpretable and computationally efficient.