In [32]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [33]:
X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")

y_train = pd.read_csv("../data/processed/y_train.csv").squeeze("columns")
y_test = pd.read_csv("../data/processed/y_test.csv").squeeze("columns")

In [34]:
def evaluate_model(model_name,model, X_test, y_test):
    
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_prob)

    return {
        "Model Name : ":model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "ROC AUC": roc_auc
    }

In [35]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [36]:
knn_result = evaluate_model("KNN",knn,X_test,y_test)
knn_result

{'Model Name : ': 'KNN',
 'Accuracy': 0.839,
 'Precision': 0.6679841897233202,
 'Recall': 0.4152334152334152,
 'F1 Score': 0.5121212121212121,
 'ROC AUC': 0.7828097743351982}

In [37]:
all_result = []

In [38]:
all_result.append(knn_result)

In [39]:
all_result

[{'Model Name : ': 'KNN',
  'Accuracy': 0.839,
  'Precision': 0.6679841897233202,
  'Recall': 0.4152334152334152,
  'F1 Score': 0.5121212121212121,
  'ROC AUC': 0.7828097743351982}]

In [40]:
comparison_df = pd.DataFrame(all_result)
comparison_df = comparison_df.round(4)
comparison_df

  Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
0           KNN     0.839      0.668  0.4152    0.5121   0.7828


# Creating Naive Bayes Model

In [41]:
nb_model = GaussianNB()
nb_model.fit(X_train,y_train)

GaussianNB()

In [42]:
nb_result = evaluate_model("Naive Bayes",nb_model,X_test,y_test)
nb_result

{'Model Name : ': 'Naive Bayes',
 'Accuracy': 0.82,
 'Precision': 0.6,
 'Recall': 0.3464373464373464,
 'F1 Score': 0.4392523364485981,
 'ROC AUC': 0.7842865978459199}

In [43]:
all_result.append(nb_result)

In [44]:
all_result

[{'Model Name : ': 'KNN',
  'Accuracy': 0.839,
  'Precision': 0.6679841897233202,
  'Recall': 0.4152334152334152,
  'F1 Score': 0.5121212121212121,
  'ROC AUC': 0.7828097743351982},
 {'Model Name : ': 'Naive Bayes',
  'Accuracy': 0.82,
  'Precision': 0.6,
  'Recall': 0.3464373464373464,
  'F1 Score': 0.4392523364485981,
  'ROC AUC': 0.7842865978459199}]

In [45]:
dt_model = DecisionTreeClassifier(random_state=42)

In [46]:
dt_model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [47]:
dt_result = evaluate_model("Decision Tree",dt_model,X_test,y_test)
dt_result

{'Model Name : ': 'Decision Tree',
 'Accuracy': 0.7825,
 'Precision': 0.46846846846846846,
 'Recall': 0.5110565110565111,
 'F1 Score': 0.4888366627497062,
 'ROC AUC': 0.6814541814541815}

In [48]:
all_result.append(dt_result)
all_result

[{'Model Name : ': 'KNN',
  'Accuracy': 0.839,
  'Precision': 0.6679841897233202,
  'Recall': 0.4152334152334152,
  'F1 Score': 0.5121212121212121,
  'ROC AUC': 0.7828097743351982},
 {'Model Name : ': 'Naive Bayes',
  'Accuracy': 0.82,
  'Precision': 0.6,
  'Recall': 0.3464373464373464,
  'F1 Score': 0.4392523364485981,
  'ROC AUC': 0.7842865978459199},
 {'Model Name : ': 'Decision Tree',
  'Accuracy': 0.7825,
  'Precision': 0.46846846846846846,
  'Recall': 0.5110565110565111,
  'F1 Score': 0.4888366627497062,
  'ROC AUC': 0.6814541814541815}]

In [49]:
comparison_df = pd.DataFrame(all_result)
comparison_df = comparison_df.round(4)

In [50]:
comparison_df

   Model Name :   Accuracy  Precision  Recall  F1 Score  ROC AUC
0            KNN    0.8390     0.6680  0.4152    0.5121   0.7828
1    Naive Bayes    0.8200     0.6000  0.3464    0.4393   0.7843
2  Decision Tree    0.7825     0.4685  0.5111    0.4888   0.6815

In [51]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    random_state=42
)

lr_model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [52]:
lr_result = evaluate_model("LogisticRegression",lr_model,X_test,y_test)

In [53]:
all_result.append(lr_result)

In [54]:
lr_balanced = LogisticRegression(
    random_state=42,
    class_weight="balanced"
)

lr_balanced.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', random_state=42)

In [55]:
lr_balanced_results = evaluate_model(
    "Balanced Logistic Regression",
    lr_balanced,
    X_test,
    y_test
)

all_result.append(lr_balanced_results)

In [56]:
comparison_df = pd.DataFrame(all_result)

comparison_df = comparison_df.round(4)

comparison_df

,Model Name :,Accuracy,Precision,Recall,F1 Score,ROC AUC
0,KNN,0.8390,0.6680,0.4152,0.5121,0.7828
1,Naive Bayes,0.8200,0.6000,0.3464,0.4393,0.7843
2,Decision Tree,0.7825,0.4685,0.5111,0.4888,0.6815
3,LogisticRegression,0.8080,0.5891,0.1867,0.2836,0.7748
4,Balanced Logistic Regression,0.7140,0.3878,0.7002,0.4991,0.7772

## Model Comparison Summary

Five machine learning models were evaluated using Accuracy, Precision, Recall, F1-score, and ROC-AUC.

### Key Findings

- KNN achieved the highest Accuracy (83.9%), Precision (66.8%), and F1-score (51.2%), making it the strongest overall performer.
- Balanced Logistic Regression achieved the highest Recall (70.0%), making it effective at identifying churned customers.
- Naive Bayes achieved the highest ROC-AUC (0.7843), indicating good ranking capability.
- Decision Tree provided moderate performance but is likely to benefit from hyperparameter tuning.
- Logistic Regression served as a strong baseline model but struggled to identify churned customers due to low Recall.

### Conclusion

There is no universally best model. The appropriate model depends on the business objective:

- If minimizing missed churned customers is the priority, Balanced Logistic Regression is preferred.
- If achieving the best overall balance across multiple metrics is the priority, KNN is the strongest candidate among the evaluated models.