In [1]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

In [2]:
df = pd.read_csv("../data/raw/Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df = df.drop(columns = ["RowNumber","CustomerId","Surname"])

In [4]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
X = df.drop("Exited",axis=1)
Y = df["Exited"]

In [9]:
print(X.shape)
print(Y.shape)

(10000, 10)
(10000,)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

In [11]:
print(X_train.shape)
print(X_test.shape)

(8000, 10)
(2000, 10)

In [12]:
numerical_features = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "HasCrCard",
    "IsActiveMember",
    "EstimatedSalary"
]

In [13]:
categorical_features = [
    "Geography",
    "Gender"
]

### Numerical Pipeline

In [14]:
numerical_transformer = Pipeline(steps = [
    ("scaler", StandardScaler())
])

In [15]:
categorical_transformer = Pipeline(
    steps=[
        (
            "encoder",
            OneHotEncoder(
                drop="first",
                handle_unknown="ignore"
            )
        )
    ]
)

In [17]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numerical_transformer,
            numerical_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)

In [18]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [19]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(8000, 11)
(2000, 11)

In [20]:
final_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", DecisionTreeClassifier(
            criterion="entropy",
            max_depth=7,
            min_samples_split=2,
            min_samples_leaf=1,
            random_state=42
        ))
    ]
)

In [21]:
final_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['Geography', 'Gender'])])),
                ('classifier',
                 DecisionTreeClassifier(criterion='entropy', max_depth=7,
                                        random_state=42))])

In [22]:
y_pred = final_pipeline.predict(X_test)

In [23]:
y_prob = final_pipeline.predict_proba(X_test)[:, 1]

In [24]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision :", precision_score(y_test, y_pred))
print("Recall :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC :", roc_auc_score(y_test, y_prob))

Accuracy : 0.857
Precision : 0.7153024911032029
Recall : 0.49385749385749383
F1 Score : 0.5843023255813954
ROC AUC : 0.8277005819378702

In [32]:
joblib.dump(
    final_pipeline,
    "../models/customer_churn_pipeline_v1.pkl"
)

['../models/customer_churn_pipeline_v1.pkl']

In [33]:
import os

os.listdir("../models")

['customer_churn_pipeline_v1.pkl', 'preprocessor.pkl']

In [34]:
loaded_pipeline = joblib.load(
    "../models/customer_churn_pipeline_v1.pkl"
)

In [35]:
loaded_pipeline.predict(X_test.head())

array([0, 0, 0, 0, 0])

In [36]:
print("Accuracy :", accuracy_score(y_test, y_pred))

Accuracy : 0.857

In [37]:
os.listdir("../models")

['customer_churn_pipeline_v1.pkl', 'preprocessor.pkl']

In [38]:
loaded_pipeline.predict(X_test.head())

array([0, 0, 0, 0, 0])